# GitHub Pages
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liangshanqing.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Site settings
title: 梁善晴的求职主页  # 网站标题（显示在浏览器标签页）
description: "复旦24届经济本26届金融硕"  # 网站描述（SEO关键信息）

# Social links
social:
  github: liangshanqing  # GitHub用户名（自动生成主页链接）
  email: sqliang24@m.fudan.edu.cn  # 联系邮箱
  wechat: lsq9142196fly  # 微信号
  instagram: liang_shanqing  # Instagram用户名
  telephone: +86 17381909152  # 联系电话

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed