#-------------------------------
# General Site Settings
title: 梁善晴的个人主页
logo: logo.png # You can add own logo.
description: Dream big, start small.


#-------------------------------
# Author Settings
author:
  name: 梁善晴
  image: 头图.jpg
  say-hello: Hi，我是 <strong>梁善晴</strong>
  bio: 复旦大学24届经济本、26届金融硕。实习历程：市场调研咨询 -> 券商行研 -> 一级PE投研，未来职业规划实体战略、分析、运营岗 or 金融投研。平时爱好音乐、读书、电影、英美剧、音乐剧舞剧和穿搭护肤。
  #eg: Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">music</a> & riding his bicycle.


#-------------------------------
# Contact links
facebook: https://www.facebook.com/people/Joan-Liang/pfbid0gn3DDjqkFfeiEvzuQhMBtsNRJKJpV3gxkQDsqeqUDK3uW2zjjnfzUvNTNJ63ZzTQl/?ref=ig_profile_ac # Add your Facebook handle
instagram: https://www.instagram.com/liang_shanqing/ # Add your Instagram handle
wechat: "lsq9142196fly" # Add your WeChat handle

#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: liang_shanqing # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-S33QWD3FMD # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
